Add some tests

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -17,6 +17,27 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.8
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+
+      - name: Run unit tests
+        run: python -W ignore -m unittest discover -s tests -p 'test_*.py'
+
+      - name: Check test results
+        run: |
+          test_exit_code=$?
+          if [ $test_exit_code -ne 0 ]; then
+            echo "Tests failed. Docker image will not be published."
+            exit $test_exit_code
+          fi
+
       - name: Build Docker image
         run: docker build -t ghcr.io/adulan/popebot:${{ github.event.release.tag_name }} .
 
